---
- name: Configure Juniper devices
  hosts: network
  connection: local
  vars_files:
    - group_vars/vault
  roles:
    # - juniper-netconf
    # - juniper-hostname
    # - juniper-interfaces
    - juniper-lldp
